"""initial schema

Revision ID: 23cd4601dd39
Revises:
Create Date: 2026-08-21 15:37:06.621164

"""
from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cd4601dd39'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CollectionSources',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('Name', sa.String(length=100), nullable=False, comment='采集源名称'),
    sa.Column('BaseUrl', sa.String(length=500), nullable=False, comment='API基础URL'),
    sa.Column('Enabled', sa.Boolean(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('AutoCollect', sa.Boolean(), server_default='0', nullable=False, comment='自动轮询采集开关'),
    sa.Column('IntervalMinutes', sa.Integer(), nullable=False, comment='轮询间隔(分钟)'),
    sa.Column('SortOrder', sa.String(length=20), server_default='time', nullable=False, comment='排序方式: time/id/hits'),
    sa.Column('LastMaxItemId', sa.Integer(), server_default='0', nullable=False, comment='上次遍历到的最大item ID（用于ID增量游标）'),
    sa.Column('LastCollectedAt', sa.DateTime(timezone=True), nullable=True, comment='上次成功采集时间'),
    sa.Column('LastStatus', sa.String(length=20), nullable=True, comment='上次采集状态: success/failed/running'),
    sa.Column('LastError', sa.Text(), nullable=True, comment='上次错误信息'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_CollectionSources'))
    )
    op.create_index('idx_collection_sources_enabled', 'CollectionSources', ['Enabled'], unique=False)
    op.create_table('DriveFiles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Provider', sa.String(length=64), nullable=False),
    sa.Column('ProviderFileId', sa.String(length=255), nullable=False),
    sa.Column('SourceUrl', sa.Text(), nullable=False),
    sa.Column('PlaybackUrl', sa.Text(), nullable=True),
    sa.Column('Mode', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Size', sa.BigInteger(), nullable=True),
    sa.Column('Status', sa.String(length=32), nullable=False),
    sa.Column('TaskId', sa.String(length=255), nullable=True),
    sa.Column('ErrorMessage', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_DriveFiles'))
    )
    op.create_index('idx_drive_files_source_url', 'DriveFiles', ['SourceUrl'], unique=False)
    op.create_index('idx_drive_files_status', 'DriveFiles', ['Status'], unique=False)
    op.create_index('uq_drive_files_provider_file', 'DriveFiles', ['Provider', 'ProviderFileId'], unique=True)
    op.create_table('Files',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID - 自增，用于关联'),
    sa.Column('Etag', sa.String(length=64), nullable=True, comment='ETag - 文件哈希值，用于缓存验证'),
    sa.Column('Size', sa.BigInteger(), nullable=True, comment='文件大小 - 字节'),
    sa.Column('Name', sa.Text(), nullable=True, comment='文件名'),
    sa.Column('SortName', sa.Text(), nullable=True, comment='排序名称 - 用于排序的文件名'),
    sa.Column('Path', sa.Text(), nullable=False, comment='文件路径 - 唯一键，用于标识文件'),
    sa.Column('CloudId', sa.String(length=255), nullable=True, comment='云盘文件 ID - 唯一键，可为空'),
    sa.Column('Provider', sa.String(length=64), nullable=True, comment='第三方存储提供商'),
    sa.Column('ProviderFileId', sa.String(length=255), nullable=True, comment='第三方存储文件 ID'),
    sa.Column('Type', sa.Enum('Image', 'Video', 'Subtitle', 'EmbeddedImage', 'Attachment', 'Data', 'Other', name='file_type_enum'), nullable=False, comment='文件类型'),
    sa.Column('FFmpeg', sa.JSON(), nullable=True, comment='ffprobe 完整输出 - JSON 格式，前端自行解析流信息'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Files'))
    )
    op.create_index('idx_files_cloud_id', 'Files', ['CloudId'], unique=True)
    op.create_index('idx_files_etag', 'Files', ['Etag'], unique=False)
    op.create_index('idx_files_path', 'Files', ['Path'], unique=True)
    op.create_index('idx_files_provider_file', 'Files', ['Provider', 'ProviderFileId'], unique=True)
    op.create_table('GuangYaPanConfig',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AccessTokenEncrypted', sa.Text(), nullable=True),
    sa.Column('RefreshTokenEncrypted', sa.Text(), nullable=True),
    sa.Column('ClientId', sa.String(length=255), nullable=True),
    sa.Column('DeviceId', sa.String(length=255), nullable=True),
    sa.Column('DefaultParentId', sa.String(length=255), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_GuangYaPanConfig'))
    )
    op.create_table('MediaItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('Type', sa.Enum('Source', 'Movie', 'Series', 'Season', 'Episode', 'BoxSet', 'Genre', 'Person', 'Studio', 'Tag', name='media_type_enum'), nullable=False, comment='媒体项类型'),
    sa.Column('Name', sa.String(length=500), nullable=True, comment='名称 - 显示名称'),
    sa.Column('Overview', sa.Text(), nullable=True, comment='简介 - 内容描述'),
    sa.Column('Tagline', sa.Text(), nullable=True, comment='标语 - 宣传标语'),
    sa.Column('StartDate', sa.DateTime(timezone=True), nullable=True, comment='开始日期 - 通用字段；Person 为出生日期，影视作品为首映/开始日期'),
    sa.Column('EndDate', sa.DateTime(timezone=True), nullable=True, comment='结束日期 - 通用字段；Person 为死亡日期，Series/Season 为结束日期'),
    sa.Column('OfficialRating', sa.String(length=255), nullable=True, comment='官方评级'),
    sa.Column('CustomRating', sa.String(length=255), nullable=True, comment='自定义评级'),
    sa.Column('CommunityRating', sa.Float(), nullable=True, comment='社区评分 - 0-10'),
    sa.Column('CriticRating', sa.Float(), nullable=True, comment='评论家评分 - 0-100'),
    sa.Column('Status', sa.Enum('Continuing', 'Ended', 'Cancelled', name='item_status_enum'), nullable=True, comment='状态'),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建日期 - UTC 时间'),
    sa.Column('DateModified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改日期 - UTC 时间'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='审计字段 - 更新时间'),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='软删除标记'),
    sa.Column('SourceId', sa.String(length=255), nullable=True, comment='来源标识 - 关联来源的唯一 ID'),
    sa.Column('SourceItemId', sa.Integer(), nullable=True, comment='来源或父级媒体项 ID'),
    sa.Column('RunTimeTicks', sa.BigInteger(), nullable=True, comment='运行时长（Ticks）'),
    sa.Column('BirthPlace', sa.String(length=500), nullable=True, comment='出生地'),
    sa.CheckConstraint('CommunityRating IS NULL OR (CommunityRating >= 0 AND CommunityRating <= 10)', name=op.f('ck_MediaItems_ck_media_items_community_rating_range')),
    sa.CheckConstraint('CriticRating IS NULL OR (CriticRating >= 0 AND CriticRating <= 100)', name=op.f('ck_MediaItems_ck_media_items_critic_rating_range')),
    sa.CheckConstraint('RunTimeTicks IS NULL OR RunTimeTicks >= 0', name=op.f('ck_MediaItems_ck_media_items_runtime_ticks_non_negative')),
    sa.CheckConstraint('StartDate IS NULL OR EndDate IS NULL OR EndDate >= StartDate', name=op.f('ck_MediaItems_ck_media_items_dates_order')),
    sa.ForeignKeyConstraint(['SourceItemId'], ['MediaItems.Id'], name=op.f('fk_MediaItems_SourceItemId_MediaItems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_MediaItems'))
    )
    op.create_index('idx_media_items_active_date_created', 'MediaItems', ['DateCreated', 'Id'], unique=False, sqlite_where=sa.text('"IsDeleted" IS 0'), postgresql_where=sa.text('"IsDeleted" IS 0'))
    op.create_index('idx_media_items_active_name', 'MediaItems', ['Name', 'Id'], unique=False, sqlite_where=sa.text('"IsDeleted" IS 0'), postgresql_where=sa.text('"IsDeleted" IS 0'))
    op.create_index('idx_media_items_community_rating', 'MediaItems', ['CommunityRating'], unique=False)
    op.create_index('idx_media_items_is_deleted', 'MediaItems', ['IsDeleted'], unique=False)
    op.create_index('idx_media_items_name', 'MediaItems', ['Name'], unique=False)
    op.create_index('idx_media_items_source_id', 'MediaItems', ['SourceId'], unique=False)
    op.create_index('idx_media_items_source_item', 'MediaItems', ['SourceItemId'], unique=False)
    op.create_index('idx_media_items_source_item_type', 'MediaItems', ['SourceItemId', 'SourceId', 'Type'], unique=False)
    op.create_index('idx_media_items_start_date', 'MediaItems', ['StartDate'], unique=False)
    op.create_index('idx_media_items_type', 'MediaItems', ['Type'], unique=False)
    op.create_index('idx_media_items_type_is_deleted', 'MediaItems', ['Type', 'IsDeleted'], unique=False)
    op.create_index('idx_media_items_type_is_deleted_created', 'MediaItems', ['Type', 'IsDeleted', 'DateCreated'], unique=False)
    op.create_index('idx_media_items_type_is_deleted_name', 'MediaItems', ['Type', 'IsDeleted', 'Name'], unique=False)
    op.create_index('idx_media_items_type_is_deleted_rating', 'MediaItems', ['Type', 'IsDeleted', 'CommunityRating'], unique=False)
    op.create_index('uq_media_items_source_key', 'MediaItems', ['SourceItemId', 'SourceId', 'Type'], unique=True, sqlite_where=sa.text('"IsDeleted" IS 0 AND "SourceItemId" IS NOT NULL AND "SourceId" IS NOT NULL'), postgresql_where=sa.text('"IsDeleted" IS 0 AND "SourceItemId" IS NOT NULL AND "SourceId" IS NOT NULL'))
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('Name', sa.String(length=255), nullable=False, comment='用户名 - 登录名称'),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False, comment='密码哈希 - PBKDF2-SHA256'),
    sa.Column('Salt', sa.String(length=255), nullable=False, comment='密码盐值 - 随机生成'),
    sa.Column('Email', sa.String(length=255), nullable=True, comment='电子邮箱'),
    sa.Column('IsAdmin', sa.Boolean(), nullable=False, comment='是否为管理员'),
    sa.Column('IsActive', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('Setting', sa.JSON(), nullable=True, comment='用户设置 - JSON 格式，如深色模式配置'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Users'))
    )
    op.create_index('idx_users_email', 'Users', ['Email'], unique=False)
    op.create_index('idx_users_name', 'Users', ['Name'], unique=False)
    op.create_table('Aliases',
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('Name', sa.Text(), nullable=False, comment='别名名称'),
    sa.Column('Source', sa.Text(), nullable=True, comment='来源 - 如 tmdb、imdb、tvdb、user 等'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_Aliases_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ItemId', 'Name', name='pk_aliases')
    )
    op.create_index('idx_aliases_name', 'Aliases', ['Name'], unique=False)
    op.create_index('idx_aliases_source', 'Aliases', ['Source', 'ItemId'], unique=False)
    op.create_table('CollectionLogs',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('SourceId', sa.Integer(), nullable=False, comment='采集源ID'),
    sa.Column('TriggerType', sa.String(length=20), nullable=False, comment='触发方式: auto/manual'),
    sa.Column('StartedAt', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('FinishedAt', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('Status', sa.String(length=20), server_default='running', nullable=False, comment='状态: running/success/failed'),
    sa.Column('NewCount', sa.Integer(), nullable=False, comment='新增视频数'),
    sa.Column('UpdateCount', sa.Integer(), nullable=False, comment='更新视频数'),
    sa.Column('ErrorCount', sa.Integer(), nullable=False, comment='失败条数'),
    sa.Column('TotalFetched', sa.Integer(), nullable=False, comment='本次拉取总条数'),
    sa.Column('ErrorMessage', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('Details', sa.JSON(), nullable=True, comment='详细信息(JSON)'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['SourceId'], ['CollectionSources.Id'], name=op.f('fk_CollectionLogs_SourceId_CollectionSources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_CollectionLogs'))
    )
    op.create_index('idx_collection_logs_source', 'CollectionLogs', ['SourceId'], unique=False)
    op.create_index('idx_collection_logs_started', 'CollectionLogs', ['StartedAt'], unique=False)
    op.create_index('idx_collection_logs_status', 'CollectionLogs', ['Status'], unique=False)
    op.create_table('FileLinks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('FileId', sa.Integer(), nullable=False, comment='文件 ID'),
    sa.Column('LinkType', sa.Enum('MediaSource', 'Image', 'Chapter', name='file_link_type_enum'), nullable=False, comment='关联类型 - MediaSource/Image/Chapter'),
    sa.Column('ImageType', sa.Enum('Primary', 'Art', 'Backdrop', 'Banner', 'Logo', 'Thumb', 'Disc', 'Box', 'BoxRear', 'Profile', 'Chapter', 'Screenshot', 'Menu', name='image_type_enum'), nullable=True, comment='图片类型 - Primary、Backdrop、Logo 等（仅图片使用）'),
    sa.Column('ImageIndex', sa.Integer(), nullable=False, comment='图片索引'),
    sa.Column('ChapterIndex', sa.Integer(), nullable=True, comment='章节索引 - 章节图片使用，标记该图片属于哪个章节'),
    sa.Column('ChapterName', sa.Text(), nullable=True, comment='章节名称 - 该图片对应的章节名称'),
    sa.Column('StartPositionTicks', sa.BigInteger(), nullable=True, comment='章节开始位置 - ticks (1 tick = 100ns)'),
    sa.Column('MarkerType', sa.Enum('Chapter', 'IntroStart', 'IntroEnd', 'CreditsStart', name='chapter_marker_type_enum'), nullable=True, comment='标记类型 - Chapter、IntroStart、CreditsStart 等'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['FileId'], ['Files.Id'], name=op.f('fk_FileLinks_FileId_Files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_FileLinks_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_FileLinks'))
    )
    op.create_index('idx_file_links_chapter', 'FileLinks', ['ItemId', 'ChapterIndex'], unique=False)
    op.create_index('idx_file_links_file', 'FileLinks', ['FileId'], unique=False)
    op.create_index('idx_file_links_item_file', 'FileLinks', ['ItemId', 'FileId'], unique=False)
    op.create_index('idx_file_links_item_image_type', 'FileLinks', ['ItemId', 'ImageType'], unique=False)
    op.create_table('ItemLinks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='源媒体项 ID'),
    sa.Column('LinkedItemId', sa.Integer(), nullable=False, comment='关联到的媒体项 ID'),
    sa.Column('PeopleType', sa.Enum('Actor', 'Director', 'Writer', 'Producer', 'Composer', 'Conductor', 'Lyricist', 'GuestStar', name='person_type_enum'), nullable=True, comment='人物类型'),
    sa.Column('PeopleRole', sa.Text(), nullable=True, comment='角色 - 人物在媒体项中的角色名称'),
    sa.Column('Order', sa.Integer(), nullable=True, comment='排序序号 - 子项在父项中的位置（如季号、集号）'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_ItemLinks_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['LinkedItemId'], ['MediaItems.Id'], name=op.f('fk_ItemLinks_LinkedItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_ItemLinks')),
    sa.UniqueConstraint('ItemId', 'LinkedItemId', name='uq_item_links_item_linked')
    )
    op.create_index('idx_item_links_item_people_type', 'ItemLinks', ['ItemId', 'PeopleType'], unique=False)
    op.create_index('idx_item_links_linked_item_item', 'ItemLinks', ['LinkedItemId', 'ItemId'], unique=False)
    op.create_index('idx_item_links_linked_item_order', 'ItemLinks', ['LinkedItemId', 'Order'], unique=False)
    op.create_index('idx_item_links_people_type', 'ItemLinks', ['PeopleType'], unique=False)
    op.create_table('UserData',
    sa.Column('UserId', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('PlaybackPositionTicks', sa.Float(), nullable=False, comment='播放位置 - 以 ticks 为单位'),
    sa.Column('PlayCount', sa.Integer(), nullable=False, comment='播放次数'),
    sa.Column('IsPlayed', sa.Boolean(), nullable=False, comment='是否已播放完成'),
    sa.Column('Rating', sa.Float(), nullable=True, comment='用户评分 - 0-10'),
    sa.Column('PlaybackRate', sa.Float(), nullable=False, comment='播放速率 - 如 0.5, 1.0, 2.0'),
    sa.Column('LastPlayedAt', sa.DateTime(timezone=True), nullable=True, comment='最后播放时间'),
    sa.Column('FavoritedAt', sa.DateTime(timezone=True), nullable=True, comment='收藏时间 - NULL 表示从未收藏'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_UserData_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('fk_UserData_UserId_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'ItemId', name=op.f('pk_UserData'))
    )
    op.create_index('idx_user_data_favorited_at', 'UserData', ['FavoritedAt'], unique=False)
    op.create_index('idx_user_data_item_user', 'UserData', ['ItemId', 'UserId'], unique=False)
    op.create_index('idx_user_data_user_favorited', 'UserData', ['UserId', 'FavoritedAt'], unique=False)
    op.create_index('idx_user_data_user_last_played', 'UserData', ['UserId', 'LastPlayedAt'], unique=False)
    op.create_index('idx_user_data_user_rating', 'UserData', ['UserId', 'Rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_data_user_rating', table_name='UserData')
    op.drop_index('idx_user_data_user_last_played', table_name='UserData')
    op.drop_index('idx_user_data_user_favorited', table_name='UserData')
    op.drop_index('idx_user_data_item_user', table_name='UserData')
    op.drop_index('idx_user_data_favorited_at', table_name='UserData')
    op.drop_table('UserData')
    op.drop_index('idx_item_links_people_type', table_name='ItemLinks')
    op.drop_index('idx_item_links_linked_item_order', table_name='ItemLinks')
    op.drop_index('idx_item_links_linked_item_item', table_name='ItemLinks')
    op.drop_index('idx_item_links_item_people_type', table_name='ItemLinks')
    op.drop_table('ItemLinks')
    op.drop_index('idx_file_links_item_image_type', table_name='FileLinks')
    op.drop_index('idx_file_links_item_file', table_name='FileLinks')
    op.drop_index('idx_file_links_file', table_name='FileLinks')
    op.drop_index('idx_file_links_chapter', table_name='FileLinks')
    op.drop_table('FileLinks')
    op.drop_index('idx_collection_logs_status', table_name='CollectionLogs')
    op.drop_index('idx_collection_logs_started', table_name='CollectionLogs')
    op.drop_index('idx_collection_logs_source', table_name='CollectionLogs')
    op.drop_table('CollectionLogs')
    op.drop_index('idx_aliases_source', table_name='Aliases')
    op.drop_index('idx_aliases_name', table_name='Aliases')
    op.drop_table('Aliases')
    op.drop_index('idx_users_name', table_name='Users')
    op.drop_index('idx_users_email', table_name='Users')
    op.drop_table('Users')
    op.drop_index('uq_media_items_source_key', table_name='MediaItems', sqlite_where=sa.text('"IsDeleted" IS 0 AND "SourceItemId" IS NOT NULL AND "SourceId" IS NOT NULL'), postgresql_where=sa.text('"IsDeleted" IS 0 AND "SourceItemId" IS NOT NULL AND "SourceId" IS NOT NULL'))
    op.drop_index('idx_media_items_type_is_deleted_rating', table_name='MediaItems')
    op.drop_index('idx_media_items_type_is_deleted_name', table_name='MediaItems')
    op.drop_index('idx_media_items_type_is_deleted_created', table_name='MediaItems')
    op.drop_index('idx_media_items_type_is_deleted', table_name='MediaItems')
    op.drop_index('idx_media_items_type', table_name='MediaItems')
    op.drop_index('idx_media_items_start_date', table_name='MediaItems')
    op.drop_index('idx_media_items_source_item_type', table_name='MediaItems')
    op.drop_index('idx_media_items_source_item', table_name='MediaItems')
    op.drop_index('idx_media_items_source_id', table_name='MediaItems')
    op.drop_index('idx_media_items_name', table_name='MediaItems')
    op.drop_index('idx_media_items_is_deleted', table_name='MediaItems')
    op.drop_index('idx_media_items_community_rating', table_name='MediaItems')
    op.drop_index('idx_media_items_active_name', table_name='MediaItems', sqlite_where=sa.text('"IsDeleted" IS 0'), postgresql_where=sa.text('"IsDeleted" IS 0'))
    op.drop_index('idx_media_items_active_date_created', table_name='MediaItems', sqlite_where=sa.text('"IsDeleted" IS 0'), postgresql_where=sa.text('"IsDeleted" IS 0'))
    op.drop_table('MediaItems')
    op.drop_table('GuangYaPanConfig')
    op.drop_index('idx_files_provider_file', table_name='Files')
    op.drop_index('idx_files_path', table_name='Files')
    op.drop_index('idx_files_etag', table_name='Files')
    op.drop_index('idx_files_cloud_id', table_name='Files')
    op.drop_table('Files')
    op.drop_index('uq_drive_files_provider_file', table_name='DriveFiles')
    op.drop_index('idx_drive_files_status', table_name='DriveFiles')
    op.drop_index('idx_drive_files_source_url', table_name='DriveFiles')
    op.drop_table('DriveFiles')
    op.drop_index('idx_collection_sources_enabled', table_name='CollectionSources')
    op.drop_table('CollectionSources')
    # ### end Alembic commands ###
