"""add favorited_at to userdata

Revision ID: add_favorited_at
Revises: c9914bb18e7e
Create Date: 2026-05-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_favorited_at'
down_revision: Union[str, Sequence[str], None] = 'add_width_height_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('FavoritedAt', sa.DateTime(timezone=True), nullable=True, comment='收藏时间 - NULL 表示从未收藏'))
    op.create_index('idx_user_data_favorited_at', 'UserData', ['FavoritedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_data_favorited_at', table_name='UserData')
    op.drop_column('UserData', 'FavoritedAt')
    # ### end Alembic commands ###
