"""add width height to files

Revision ID: c9914bb18e7e
Revises: 
Create Date: 2026-04-25 13:13:00.990585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9914bb18e7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID - 自增，用于关联'),
    sa.Column('Etag', sa.String(length=64), nullable=True, comment='ETag - 文件哈希值，用于缓存验证'),
    sa.Column('Size', sa.BigInteger(), nullable=True, comment='文件大小 - 字节'),
    sa.Column('Name', sa.Text(), nullable=True, comment='文件名'),
    sa.Column('SortName', sa.Text(), nullable=True, comment='排序名称 - 用于排序的文件名'),
    sa.Column('Path', sa.Text(), nullable=False, comment='文件路径 - 唯一键，用于标识文件'),
    sa.Column('CloudId', sa.String(length=255), nullable=True, comment='云盘文件 ID - 唯一键，可为空'),
    sa.Column('Type', sa.Enum('Image', 'Video', 'Audio', 'Subtitle', 'EmbeddedImage', 'Attachment', 'Data', 'Lyrics', 'Nfo', 'Other', name='file_type_enum'), nullable=False, comment='文件类型'),
    sa.Column('FFmpeg', sa.JSON(), nullable=True, comment='ffprobe 完整输出 - JSON 格式，前端自行解析流信息'),
    sa.Column('Width', sa.Integer(), nullable=True, comment='图片/视频宽度 - 像素'),
    sa.Column('Height', sa.Integer(), nullable=True, comment='图片/视频高度 - 像素'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Files')),
    sa.UniqueConstraint('CloudId', name=op.f('uq_Files_CloudId')),
    sa.UniqueConstraint('Path', name=op.f('uq_Files_Path'))
    )
    op.create_index('idx_files_cloud_id', 'Files', ['CloudId'], unique=True)
    op.create_index('idx_files_etag', 'Files', ['Etag'], unique=False)
    op.create_index('idx_files_path', 'Files', ['Path'], unique=True)
    op.create_index(op.f('ix_Files_Etag'), 'Files', ['Etag'], unique=False)
    op.create_table('MediaItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('Type', sa.Enum('Source', 'Movie', 'Series', 'Season', 'Episode', 'BoxSet', 'Genre', 'Person', 'Studio', 'Tag', 'Folder', 'TvChannel', 'MusicVideo', 'VirtualFolder', 'UserRootFolder', 'UserView', 'AggregateFolder', 'Playlist', 'PhotoAlbum', 'MusicAlbum', 'MusicArtist', 'MusicGenre', 'Video', 'Audio', 'AudioBook', 'Book', 'Trailer', 'Program', 'Channel', 'LiveTvChannel', 'LiveTvProgram', 'Photo', 'TrailerExtra', 'ThemeSong', 'ThemeVideo', name='media_type_enum'), nullable=False, comment='媒体项类型'),
    sa.Column('Name', sa.Text(), nullable=True, comment='名称 - 显示名称'),
    sa.Column('Overview', sa.Text(), nullable=True, comment='简介 - 内容描述'),
    sa.Column('Tagline', sa.Text(), nullable=True, comment='标语 - 宣传标语'),
    sa.Column('PremiereDate', sa.DateTime(timezone=True), nullable=True, comment='首映日期 - UTC 时间'),
    sa.Column('EndDate', sa.DateTime(timezone=True), nullable=True, comment='结束日期 - UTC 时间'),
    sa.Column('StartDate', sa.DateTime(timezone=True), nullable=True, comment='开始日期 - UTC 时间'),
    sa.Column('RunTimeTicks', sa.BigInteger(), nullable=True, comment='运行时长 - 以 ticks 为单位'),
    sa.Column('ProductionYear', sa.Integer(), nullable=True, comment='生产年份'),
    sa.Column('OfficialRating', sa.String(length=255), nullable=True, comment='官方评级'),
    sa.Column('CustomRating', sa.String(length=255), nullable=True, comment='自定义评级'),
    sa.Column('CommunityRating', sa.Float(), nullable=True, comment='社区评分 - 0-10'),
    sa.Column('CriticRating', sa.Float(), nullable=True, comment='评论家评分 - 0-100'),
    sa.Column('Status', sa.Enum('Continuing', 'Ended', 'Cancelled', name='item_status_enum'), nullable=True, comment='状态'),
    sa.Column('DisplayOrder', sa.Enum('Default', 'Aired', 'Absolute', 'Dvd', 'Production', name='display_order_enum'), nullable=True, comment='显示顺序'),
    sa.Column('ChannelNumber', sa.String(length=50), nullable=True, comment='频道号'),
    sa.Column('AlbumId', sa.Integer(), nullable=True, comment='专辑 ID'),
    sa.Column('ProductionLocations', sa.Text(), nullable=True, comment='制作地点 - JSON 数组'),
    sa.Column('RemoteTrailers', sa.Text(), nullable=True, comment='远程预告片 - JSON 数组'),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建日期 - UTC 时间'),
    sa.Column('DateModified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改日期 - UTC 时间'),
    sa.Column('DateLastRefreshed', sa.DateTime(timezone=True), nullable=True, comment='最后刷新日期'),
    sa.Column('DateLastSaved', sa.DateTime(timezone=True), nullable=True, comment='最后保存日期'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('PresentationUniqueKey', sa.Text(), nullable=True, comment='展示唯一键'),
    sa.Column('PreferredMetadataLanguage', sa.String(length=50), nullable=True, comment='首选元数据语言'),
    sa.Column('PreferredMetadataCountryCode', sa.String(length=10), nullable=True, comment='首选元数据国家代码'),
    sa.Column('LockedFields', sa.Text(), nullable=True, comment='锁定字段 - JSON 数组'),
    sa.ForeignKeyConstraint(['AlbumId'], ['MediaItems.Id'], name=op.f('fk_MediaItems_AlbumId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_MediaItems'))
    )
    op.create_index('idx_media_items_community_rating', 'MediaItems', ['CommunityRating'], unique=False)
    op.create_index('idx_media_items_is_deleted', 'MediaItems', ['IsDeleted'], unique=False)
    op.create_index('idx_media_items_name', 'MediaItems', ['Name'], unique=False)
    op.create_index('idx_media_items_premiere_date', 'MediaItems', ['PremiereDate'], unique=False)
    op.create_index('idx_media_items_production_year', 'MediaItems', ['ProductionYear'], unique=False)
    op.create_index('idx_media_items_source_name_unique', 'MediaItems', ['Name'], unique=True, postgresql_where=sa.text('"Type" = \'Source\''))
    op.create_index('idx_media_items_type', 'MediaItems', ['Type'], unique=False)
    op.create_index(op.f('ix_MediaItems_IsDeleted'), 'MediaItems', ['IsDeleted'], unique=False)
    op.create_index(op.f('ix_MediaItems_Type'), 'MediaItems', ['Type'], unique=False)
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('Name', sa.String(length=255), nullable=False, comment='用户名 - 登录名称'),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False, comment='密码哈希 - PBKDF2-SHA256'),
    sa.Column('Salt', sa.String(length=255), nullable=False, comment='密码盐值 - 随机生成'),
    sa.Column('Email', sa.String(length=255), nullable=True, comment='电子邮箱'),
    sa.Column('IsAdmin', sa.Boolean(), nullable=False, comment='是否为管理员'),
    sa.Column('IsActive', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('Setting', sa.JSON(), nullable=True, comment='用户设置 - JSON 格式，如深色模式配置'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Users'))
    )
    op.create_index('idx_users_email', 'Users', ['Email'], unique=False)
    op.create_index('idx_users_name', 'Users', ['Name'], unique=False)
    op.create_table('Aliases',
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('Name', sa.Text(), nullable=False, comment='别名名称'),
    sa.Column('Source', sa.Text(), nullable=True, comment='来源 - 如 tmdb、imdb、tvdb、user 等'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_Aliases_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ItemId', 'Name', name='pk_aliases')
    )
    op.create_index('idx_aliases_item', 'Aliases', ['ItemId'], unique=False)
    op.create_index('idx_aliases_name', 'Aliases', ['Name'], unique=False)
    op.create_index('idx_aliases_source', 'Aliases', ['Source', 'ItemId'], unique=False)
    op.create_table('FileLinks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('FileId', sa.Integer(), nullable=False, comment='文件 ID'),
    sa.Column('ImageType', sa.Enum('Primary', 'Art', 'Backdrop', 'Banner', 'Logo', 'Thumb', 'Disc', 'Box', 'BoxRear', 'Profile', 'Chapter', 'Screenshot', 'Menu', name='image_type_enum'), nullable=True, comment='图片类型 - Primary、Backdrop、Logo 等（仅图片使用）'),
    sa.Column('ImageIndex', sa.Integer(), nullable=False, comment='图片索引'),
    sa.Column('ChapterIndex', sa.Integer(), nullable=True, comment='章节索引 - 章节图片使用，标记该图片属于哪个章节'),
    sa.Column('ChapterName', sa.Text(), nullable=True, comment='章节名称 - 该图片对应的章节名称'),
    sa.Column('StartPositionTicks', sa.BigInteger(), nullable=True, comment='章节开始位置 - ticks (1 tick = 100ns)'),
    sa.Column('MarkerType', sa.Enum('Chapter', 'IntroStart', 'IntroEnd', 'CreditsStart', name='chapter_marker_type_enum'), nullable=True, comment='标记类型 - Chapter、IntroStart、CreditsStart 等'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['FileId'], ['Files.Id'], name=op.f('fk_FileLinks_FileId_Files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_FileLinks_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_FileLinks'))
    )
    op.create_index('idx_file_links_chapter', 'FileLinks', ['ItemId', 'ChapterIndex'], unique=False)
    op.create_index('idx_file_links_file', 'FileLinks', ['FileId'], unique=False)
    op.create_index('idx_file_links_item', 'FileLinks', ['ItemId'], unique=False)
    op.create_table('ItemLinks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 - 自增整数 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='源媒体项 ID'),
    sa.Column('LinkedItemId', sa.Integer(), nullable=False, comment='关联到的媒体项 ID'),
    sa.Column('Type', sa.Enum('Genre', 'Studio', 'Tag', 'Keyword', 'ProductionLocation', 'BoxSet', 'Person', 'Source', 'SeriesSeason', 'SeasonEpisode', name='item_link_type_enum'), nullable=False, comment='关联类型 - Genre、Studio、Tag、Person、Source 等'),
    sa.Column('PeopleType', sa.Enum('Actor', 'Director', 'Writer', 'Producer', 'Composer', 'Conductor', 'Lyricist', 'GuestStar', name='person_type_enum'), nullable=True, comment='人物类型 - 仅 Person 类型使用'),
    sa.Column('PeopleRole', sa.Text(), nullable=True, comment='角色 - 人物在媒体项中的角色名称（仅 Person 类型使用）'),
    sa.Column('SourceId', sa.Text(), nullable=True, comment='来源 ID - 关联来源的标识（仅 Source 类型使用）'),
    sa.Column('SourceLink', sa.Text(), nullable=True, comment='来源链接 - 关联来源的链接或路径（仅 Source 类型使用）'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_ItemLinks_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['LinkedItemId'], ['MediaItems.Id'], name=op.f('fk_ItemLinks_LinkedItemId_MediaItems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_ItemLinks')),
    sa.UniqueConstraint('ItemId', 'LinkedItemId', 'Type', name='uq_item_links_item_linked_type')
    )
    op.create_index('idx_item_links_item_id', 'ItemLinks', ['ItemId'], unique=False)
    op.create_index('idx_item_links_linked_item_id', 'ItemLinks', ['LinkedItemId'], unique=False)
    op.create_index('idx_item_links_people_type', 'ItemLinks', ['PeopleType'], unique=False)
    op.create_index('idx_item_links_type', 'ItemLinks', ['Type'], unique=False)
    op.create_table('UserData',
    sa.Column('UserId', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('IsFavorite', sa.Boolean(), nullable=False, comment='是否收藏'),
    sa.Column('Likes', sa.Boolean(), nullable=True, comment='是否点赞'),
    sa.Column('PlaybackPositionTicks', sa.Float(), nullable=False, comment='播放位置 - 以 ticks 为单位'),
    sa.Column('PlayCount', sa.Integer(), nullable=False, comment='播放次数'),
    sa.Column('IsPlayed', sa.Boolean(), nullable=False, comment='是否已播放完成'),
    sa.Column('Rating', sa.Float(), nullable=True, comment='用户评分 - 0-10'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_UserData_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('fk_UserData_UserId_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'ItemId', name=op.f('pk_UserData'))
    )
    op.create_index('idx_user_data_is_favorite', 'UserData', ['IsFavorite'], unique=False)
    op.create_index('idx_user_data_item_id', 'UserData', ['ItemId'], unique=False)
    op.create_index('idx_user_data_user_id', 'UserData', ['UserId'], unique=False)
    op.create_table('UserItemShares',
    sa.Column('UserId', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('ItemId', sa.Integer(), nullable=False, comment='媒体项 ID'),
    sa.Column('ShareLevel', sa.Enum('Read', 'Write', 'Admin', name='share_level_enum'), nullable=False, comment='分享级别'),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 创建时间'),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False, comment='审计字段 - 更新时间'),
    sa.ForeignKeyConstraint(['ItemId'], ['MediaItems.Id'], name=op.f('fk_UserItemShares_ItemId_MediaItems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('fk_UserItemShares_UserId_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'ItemId', name=op.f('pk_UserItemShares'))
    )
    op.create_index('idx_user_item_shares_item_id', 'UserItemShares', ['ItemId'], unique=False)
    op.create_index('idx_user_item_shares_user_id', 'UserItemShares', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_item_shares_user_id', table_name='UserItemShares')
    op.drop_index('idx_user_item_shares_item_id', table_name='UserItemShares')
    op.drop_table('UserItemShares')
    op.drop_index('idx_user_data_user_id', table_name='UserData')
    op.drop_index('idx_user_data_item_id', table_name='UserData')
    op.drop_index('idx_user_data_is_favorite', table_name='UserData')
    op.drop_table('UserData')
    op.drop_index('idx_item_links_type', table_name='ItemLinks')
    op.drop_index('idx_item_links_people_type', table_name='ItemLinks')
    op.drop_index('idx_item_links_linked_item_id', table_name='ItemLinks')
    op.drop_index('idx_item_links_item_id', table_name='ItemLinks')
    op.drop_table('ItemLinks')
    op.drop_index('idx_file_links_item', table_name='FileLinks')
    op.drop_index('idx_file_links_file', table_name='FileLinks')
    op.drop_index('idx_file_links_chapter', table_name='FileLinks')
    op.drop_table('FileLinks')
    op.drop_index('idx_aliases_source', table_name='Aliases')
    op.drop_index('idx_aliases_name', table_name='Aliases')
    op.drop_index('idx_aliases_item', table_name='Aliases')
    op.drop_table('Aliases')
    op.drop_index('idx_users_name', table_name='Users')
    op.drop_index('idx_users_email', table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_MediaItems_Type'), table_name='MediaItems')
    op.drop_index(op.f('ix_MediaItems_IsDeleted'), table_name='MediaItems')
    op.drop_index('idx_media_items_type', table_name='MediaItems')
    op.drop_index('idx_media_items_source_name_unique', table_name='MediaItems', postgresql_where=sa.text('"Type" = \'Source\''))
    op.drop_index('idx_media_items_production_year', table_name='MediaItems')
    op.drop_index('idx_media_items_premiere_date', table_name='MediaItems')
    op.drop_index('idx_media_items_name', table_name='MediaItems')
    op.drop_index('idx_media_items_is_deleted', table_name='MediaItems')
    op.drop_index('idx_media_items_community_rating', table_name='MediaItems')
    op.drop_table('MediaItems')
    op.drop_index(op.f('ix_Files_Etag'), table_name='Files')
    op.drop_index('idx_files_path', table_name='Files')
    op.drop_index('idx_files_etag', table_name='Files')
    op.drop_index('idx_files_cloud_id', table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
