"""remove likes from userdata

Revision ID: remove_likes
Revises: add_favorited_at
Create Date: 2026-05-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_likes'
down_revision: Union[str, Sequence[str], None] = 'add_favorited_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserData', 'Likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('Likes', sa.Boolean(), nullable=True, comment='是否点赞'))
    # ### end Alembic commands ###
